@startuml Inscription

title Inscription

|Administrateur|
start
:Créer un lien d'inscription et l'envoie à l'utilisateur en fonction de leur rôle;
|Système|
:Envoie le lien à l'utilisateur par email;
|Utilisateur|
:Clique sur le lien d'inscription reçu par email;
|Système|
:Ouvre la page d'inscription;
|Utilisateur|
:Arrive sur la page d'inscription;
:Remplir le formulaire d'inscription;
:Valider le formulaire;
|Système|
while (Il y aune erreur) is (Oui)
  :Affiche un message d'erreur;
  :Redirige vers la page d'inscription;
  |Utilisateur|
  :Remplir le formulaire d'inscription;
  :Valider le formulaire;
end while
|Système|
:Affiche un message de succès;
|Administrateur|
:Reçoit une notification de la nouvelle inscription;
:Valide ou refuse l'inscription de l'utilisateur;
|Système|
if (L'inscription est validée?) then (Oui)
  :Active le compte de l'utilisateur;
  :Envoie un email de confirmation à l'utilisateur;
else (Non)
  :Envoie un email de refus à l'utilisateur;
endif
stop
@enduml