@startuml Suppression Classe

title Suppression d'une classe

|Enseignant|
start
:Demande de suppression d'une classe;
|Système|
:Suppression de la classe;
:Notification de la suppression à l'enseignant;
stop


@enduml