services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: symfony
    container_name: symfony_php
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - database
    networks:
      - app_network
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/backend
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network
  angular:
    image: node:20
    container_name: angular
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start -- --host 0.0.0.0"
    ports:
      - "4300:4200"
    networks:
      - app_network
  database:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --innodb-buffer-pool-size=256M
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot --silent"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
  database_test:
    image: mysql:8
    container_name: mysql_test
    environment:
      MYSQL_DATABASE: app_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3308:3306"
    volumes:
    - db_test_data:/var/lib/mysql
    networks:
    - app_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot --silent"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_workspace:/opt/cloudbeaver/workspace
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network

volumes:
  db_data:
  db_test_data:
  cloudbeaver_workspace:

networks:
  app_network: