@startuml Digiforma

' ======================
' Classes
' ======================

class User {
  -user_id : int
  -last_name : string
  -first_name : string
  -email : string
  -password : string
  -role : string
  -created_at : datetime
}

class Teacher extends User {
  -subject : string
}

class Student extends User {
  -enrollment_date : date
}

class Parent extends User {
  -child_id : [int]
}



class Class {
  -class_id : int
  -class_name : string
  -class_description : text
  -teacher_id : int
}

class Course {
  -course_id : int
  -course_title : string
  -description : text
  -resource_file : string
  -video_url : string
  -class_id : int
}

class Activity {
  -activity_id : int
  -activity_type : string
  -activity_title : string
  -description : text
  -due_date : date
  -course_id : int
}

class Message {
  -message_id : int
  -content : text
  -sent_at : datetime
  -sender_id : int
  -receiver_id : int
}

class Progress {
  -progress_id : int
  -progress_percent : decimal
  -grade : decimal
  -activity_id : int
  -course_id : int
  -student_id : int
}

class Report {
  -report_id : int
  -report_type : string
  -data : text
  -generated_at : datetime
  -course_id : int
  -class_id : int
  -user_id : int
}

' ======================
' Relations
' ======================

Teacher "1" -- "0..*" Class : teach
Class "1" -- "0..*" Course : contains
Course "1" -- "0..*" Activity : includes

User "1" -- "0..*" Message : send >
User "1" -- "0..*" Message : receive

Student "1" -- "0..*" Progress : has_progress
Course "1" -- "0..*" Progress : is_followed_in
Activity "1" -- "0..*" Progress : evaluates

User "1" -- "0..*" Report : generates
Class "1" -- "0..*" Report : analysis
Course "1" -- "0..*" Report : analysis

@enduml